- name: setup mysql database 
  hosts: all
  remote_user: pi
  become: yes

  tasks:
  - name: Create a new database
    mysql_db:
      name: "housestock-{{ env }}"
      state: present
      login_user: 'root'
      login_password: '{{ root_pass }}'
  
  - name: Set application user
    mysql_user:
      login_host: 'localhost'
      login_user: 'root'
      login_password: '{{ root_pass }}'
      host: '%'
      name: 'housestock-{{ env }}'
      password: '{{ application_user_password }}'
      priv: 'housestock-{{ env }}.*:SELECT,INSERT,DELETE,UPDATE'
      state: present
        
  - name: Set migration user
    mysql_user:
      login_host: 'localhost'
      login_user: 'root'
      login_password: '{{ root_pass }}'
      host: '%'
      name: 'housestock-migration-{{ env }}'
      password: '{{ migration_user_password }}'
      priv: 'housestock-{{ env }}.*:ALTER,CREATE,SELECT,INSERT,DELETE,UPDATE,INDEX,DROP'
      state: present
      